### ISSUE TITLE
Clear canvas and initial text

### ISSUE THREAD

**Issue by yoksanherlie** [Anshuman-Verma/canvas#7]
I will just do the simple todo in the README

- Add button to clear screen.
- Add some default text on initial screen like "Click to draw".

**Comment by anshumanv** [comment]
Good to have you @yoksanherlie !
Please send a PR, I've been waiting for these features :smile:

**Comment by yoksanherlie** [comment]
@anshumanv Done!
Glad to help :smile:

Tell me if you want some more improvement :wink:

**Comment by anshumanv** [comment]
@yoksanherlie see if you can help with #3 and stuff exiting in the README.md, this issue has been solved in #8 so closing this. :+1:
